### PR TITLE
Fix vmdisplay compiling issue

### PR DESCRIPTION
**Pull request by xinyunliu**
Add missing dependency: -lpthread

Signed-off-by: Xinyun Liu <xinyun.liu@intel.com>

### CODE REVIEW

**Comment by YinThong** [comment]
I already fix it and create the PR. Actually you will build pass if add it CFLAG --copy-dt-needed-entries

**Comment by YinThong** [comment]
Sorry i miss out your PR.. @satyeshwar Please take this and ignore my PR https://github.com/intel/ias/pull/32

**Comment by satyeshwar** [comment]
Hi,
I am accepting this change due to time sensitivity. However, please remember a few things. 
1) The format of commit message should always be like this: 
Component: Header

Message

So for example, you should mention the component being Makefile.am. For now, I have made this change myself.

2) vmdisplay was compiling after adding in https://github.com/intel/ias/pull/28. So what compilation issue is this fixing? You need to be more explicit in your commit messages.

This has been merged now. Thanks!

**Comment by satyeshwar** [comment]
Please mention in commit message "Fixes #XYZ" in the future as it will automatically close that issue.

**Pull request closed without merging**
